# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FBSampleSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FBSampleSwift
	pod "GBHFacebookImagePicker", '~> 2.4'

  target 'FBSampleSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FBSampleSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
